### ISSUE TITLE
Community pages error due to incorrect SQL query

### ISSUE THREAD

**Issue by WillTheDeveloper** [WillTheDeveloper/StudyPortal#11]
So, the following pages cannot be currently accessed:

- Trending
- Popular
- Communities

All give "404" errors.

This is because, Laravel is trying to query "Trending" or the associated page for the community user page which is a different route entirely.

```php
public function profile($id)
    {
        return view('communityuser', [
            'user' => User::query()->where('users.id', $id)->findOrFail($id)
        ]);
    }
```

This is the page that should display the user profile.

But that should not be being executed as this route is being hit from the routes to the controller:

*Which is left blank for testing purposes*

```php
public function popular()
    {
        return view('popular');
    }

    public function communities()
    {
        return view('communities');
    }

    public function trending()
    {
        return view('trending');
    }
```

When trying to open one of the three pages outlined in the beginning, I noticed this incorrect query being executed which brought me to this conclusion. Laravel is trying to find a user with the ID of "trending" or one of the three outlined above which is incorrect.

```sql
select * from `users` where `users`.`id` = 'trending' and `users`.`id` = 'trending' limit 1
```

Not sure why this is happening, I will outline the web routes for these below.

```php

Route::get('/community/post/{id}', [Community::class, 'post'])
    ->middleware('auth')
    ->name('community.post');

Route::get('/community/{id}', [Community::class, 'profile'])
    ->middleware('auth')
    ->name('community.profile');

Route::get('/community/popular', [Community::class, 'popular'])
    ->middleware('auth')
    ->name('community.popular');

Route::get('/community/communities', [Community::class, 'communities'])
    ->middleware('auth')
    ->name('community.communities');

Route::get('/community/trending', [Community::class, 'trending'])
    ->middleware('auth')
    ->name('community.trending');

```

**Comment by WillTheDeveloper** [comment]
Fixed in this commit: https://github.com/WillTheDeveloper/StudyPortal/commit/f0f4d8bc78c59839253313841b645f0cfa0f4dc0

Updated the route so they are not the same whatsoever. The community user now uses route "/user/{id}".

**Comment by mauro-balades** [comment]
👍🏽
