### ISSUE TITLE
Bool being returned in collection on blade

### ISSUE THREAD

**Issue by WillTheDeveloper** [WillTheDeveloper/StudyPortal#12]
Originated from: https://github.com/WillTheDeveloper/StudyPortal/commit/2b515a4373fe8f7da2a80f57ea480a74ddf545ee

I am trying to get "/community/communities" to return all the different subjects that are found in the database.

When I reference the table inside the foreach statement which the collection is generated in the controller, it looks for a bool when the data being stored is not a boolean type and should just be a string of text.

This is the controller:
```php
public function communities()
    {
        return view('communities', [
            'subject' => Subject::all()
        ]);
    }
```

This is the migration for subjects:
```php
public function up()
    {
        Schema::create('subjects', function (Blueprint $table) {
            $table->id();
            $table->string('subject')->unique();
            $table->timestamps();
        });
    }
```

This is the GET request in the routes file in case your wondering:
```php
Route::get('/community/communities', [Community::class, 'communities'])
    ->middleware('auth')
    ->name('community.communities');
```

This is the start of the foreach statement in the blade file:
```blade
@forelse($posts as $post)
```

While this issue is a thing, I have commented out a lot of the blade file to avoid experiencing any errors.

**Comment by WillTheDeveloper** [comment]
Issue fixed after doing:

```shell
php artisan migrate:refresh
```

**Comment by WillTheDeveloper** [comment]
Issue persists when creating records in the "subject_user" database table.

**Comment by WillTheDeveloper** [comment]
Suspected query that is causing the issue:

![image](https://user-images.githubusercontent.com/78596837/143688210-10deb6e0-3158-473e-920e-697a53e58253.png)

**Comment by WillTheDeveloper** [comment]
Implemented casts? https://github.com/WillTheDeveloper/StudyPortal/commit/5e3e4ba9ee6322035266619ad12026f962084ade

**Comment by WillTheDeveloper** [comment]
Fixed: https://github.com/WillTheDeveloper/StudyPortal/commit/ed72958104ab2a2f58ef0a4ee23d15ba1882c1ba

Changed the variable name that contained the collection data. Laravel must be getting the names confused since they was identical.

**Comment by mauro-balades** [comment]
👍🏽
