### ISSUE TITLE
Github auth needs a password when creating the user

### ISSUE THREAD

**Issue by WillTheDeveloper** [WillTheDeveloper/StudyPortal#13]
I have setup Github auth to work with the login system.

All the other details regarding the user are able to be retrieved from Github except for passwords for obvious reasons.

I did move the Third party authentication to its own controller.

I have added the following fields to the users table, copied from the migration:

```php
$table->integer('github_id')->nullable(true)->default(null);
$table->string('github_token')->nullable(true)->default(null);
$table->string('github_refresh_token')->nullable(true)->default(null);
```

Maybe I will just generate a password automatically then let the user change it accordingly.

This is the new controller that handles the callback from github once they have authenticated themselves on it:

```php
public function githubCallback()
    {
        $githubUser = Socialite::driver('github')->user();

        $user = \App\Models\User::query()->where('users.github_id', $githubUser->id)->first();

        if ($user) {
            $user->update([
                'github_token' => $githubUser->token,
                'github_refresh_token' => $githubUser->refreshToken,
            ]);
        } else {
            $user = \App\Models\User::query()->create([
                'name' => $githubUser->name,
                'email' => $githubUser->email,
                'github_id' => $githubUser->id,
                'github_token' => $githubUser->token,
                'github_refresh_token' => $githubUser->refreshToken,
            ]);
        }

        Auth::login($user);

        return redirect('/dashboard');
    }
```

The password is also hashed and I am worried about making a security vulnerability. Further investigation is required.

**Comment by WillTheDeveloper** [comment]
Original commit this issue originates from: https://github.com/WillTheDeveloper/StudyPortal/commit/355b5528ae910e22572df4feaec934b04136eb6f

**Comment by mauro-balades** [comment]
@WillTheDeveloper Also, try using the stateless method to avoid any unexpected errors and having to state that `there is no sessions stored.`.

```
$githubUser = Socialite::driver('github')->stateless()->user();
```

https://laracasts.com/discuss/channels/laravel/understand-socialite-stateless-flow

**Comment by mauro-balades** [comment]
also, instead of doing one function for every service, do one general function to handle all of them.

**Comment by WillTheDeveloper** [comment]
Do you just absorb knowledge or have you used Laravel before? Also, noted.

**Comment by mauro-balades** [comment]
I have used laravel before

**Comment by WillTheDeveloper** [comment]
Wow, okay.

**Comment by mauro-balades** [comment]
@WillTheDeveloper is there a way to implement the github auth rn?

**Comment by WillTheDeveloper** [comment]
The github auth is already implemented as there is a route that will register you with your Github account but their is no password and I need to sort out that stateless thing.

**Comment by WillTheDeveloper** [comment]
This has been moved to the roadmap. This isn't a major issue as its not currently available on the front-end. It will be addressed soon. https://github.com/Study-Portal/roadmap/issues/12

**Comment by mauro-balades** [comment]
👍🏽
