### ISSUE TITLE
[BUG]: Cant join a community

### ISSUE THREAD

**Issue by NichTheDev** [WillTheDeveloper/StudyPortal#130]
### What happened?

When i try to join a community it takes me to 403 page saying i dont have permission to do that.

### Browser

Firefox

### When did it occur?

16/12/2022 - 12:40

**Comment by WillTheDeveloper** [comment]
Fixed in https://github.com/WillTheDeveloper/StudyPortal/commit/7a0c37180d7c2f38419c466fa5788baee96902eb
