### ISSUE TITLE
Permission issue where students cannot view details of assignment.

### ISSUE THREAD

**Issue by WillTheDeveloper** [WillTheDeveloper/StudyPortal#3]
When you are on this page:

![image](https://user-images.githubusercontent.com/78596837/141192500-0635ab22-1616-4d7c-b43e-8b9ebbc916f4.png)

And you try to view the assignment as a student, you get an error.

![image](https://user-images.githubusercontent.com/78596837/141192546-949878ee-5383-4dbd-8a7f-6ad11800b1e9.png)

**Comment by WillTheDeveloper** [comment]
Issue resolved. Updated middleware for this specific route. Commit: https://github.com/WillTheDeveloper/StudyPortal/commit/fa9b682256020b2bf17fb49fdc2f424b974c55cf

**Comment by mauro-balades** [comment]
👍🏽
