### ISSUE TITLE
[TODO] Update the email 

### ISSUE THREAD

**Issue by mauro-balades** [WillTheDeveloper/StudyPortal#34]
In the verification email, change the org name and logotype.

![image](https://user-images.githubusercontent.com/91018726/156358464-fcf773b6-c679-405d-97ba-c229f776d062.png)

**Comment by WillTheDeveloper** [comment]
I am aware of this. Haven't got the stage of redesigning it.

**Comment by mauro-balades** [comment]
👍🏽
