### ISSUE TITLE
Add common sections to components.

### ISSUE THREAD

**Issue by mauro-balades** [WillTheDeveloper/StudyPortal#41]
Here is one idea. You could change common sections of `study portal` and convert them to a component.

Why?
* This will make every HTML element update for every page instead of updating every page one by one.
    * e.g. You update a button in the navbar to another color.

What components?
* Buttons
* Navbar
* Post container

and more stuff

**Comment by WillTheDeveloper** [comment]
I should really start using templates and slots. You have a really good point. It is something I will do in the future.

I will add it to the roadmap and I will close this issue.

**Comment by mauro-balades** [comment]
👌

**Comment by WillTheDeveloper** [comment]
Added to the roadmap: https://github.com/Study-Portal/roadmap/issues/20

**Comment by mauro-balades** [comment]
👍🏽
