### ISSUE TITLE
here is the answer: it is a very  good giraffe

### ISSUE THREAD

**Issue by tokorv** [WillTheDeveloper/StudyPortal#44]
here is the answer: it is a very  good giraffe

_Originally posted by @mauro-balades in https://github.com/WillTheDeveloper/StudyPortal/discussions/43#discussioncomment-2351520_

**Comment by tokorv** [comment]
This is an issue.

**Comment by mauro-balades** [comment]
> This is an issue.

mhm

**Comment by mauro-balades** [comment]
@WillTheDeveloper close this issue, it is off-topic
