### ISSUE TITLE
Don't show the homepage if logged in

### ISSUE THREAD

**Issue by mauro-balades** [WillTheDeveloper/StudyPortal#62]
### What happened?

When login, maybe redirect to the dashboard instead of showing the homepage.

**Comment by mauro-balades** [comment]
Should I do it?

**Comment by mauro-balades** [comment]
No...

If the user has logged in, the user should be redirected to the dashboard although he goes to `/`.

e.g.
```php
if (User::exists()) {
    redirect("/dashboard")
}
```

**Comment by WillTheDeveloper** [comment]
Do you mean, like the way Github does it? Where if your logged in, it just takes you to the dashboard straight away?

**Comment by mauro-balades** [comment]
yes

**Comment by WillTheDeveloper** [comment]
Ohhhhhhhh, yeah that could work. But I do want to test it myself in a separate branch before we commit to master.

Also, that's the wrong check, you want to do:

```
auth()->check()
```

As this will return a true or false value to determine if the user is logged in or not.

Exists is wrong and would just determine if the user exists in the database.

**Comment by mauro-balades** [comment]
> Ohhhhhhhh, yeah that could work. But I do want to test it myself in a separate branch before we commit to master.
> 
> Also, that's the wrong check, you want to do:
> 
> ```
> auth()->check()
> ```
> 
> As this will return a true or false value to determine if the user is logged in or not.
> 
> Exists is wrong and would just determine if the user exists in the database.

It was a mock example, idk the functions yet...

**Comment by WillTheDeveloper** [comment]
I think if you add "guest" middleware to these routes it will redirect to dashboard @mauro-balades

**Comment by WillTheDeveloper** [comment]
Can do, give it a try. From something that I read, I believe it will just redirect to the dashboard. Do it in another branch!

**Comment by mauro-balades** [comment]
> Can do, give it a try. From something that I read, I believe it will just redirect to the dashboard. Do it in another branch!

aight
