### ISSUE TITLE
Users able to access each other's kanban boards

### ISSUE THREAD

**Issue by WillTheDeveloper** [WillTheDeveloper/StudyPortal#69]
People are able to edit and manage other people's kanban boards and the contents which is not good whatsoever.

**Comment by mauro-balades** [comment]
You are saying, they are not supposed to edit each other's kanban boards?

**Comment by WillTheDeveloper** [comment]
Nah, they can delete it and all that stuff which is pretty bad. I totally overlooked it.

**Comment by mauro-balades** [comment]
can't u check if the user is "allowed" to be in there? if not, send a 404 error.

**Comment by WillTheDeveloper** [comment]
Yeah you could, make a middleware
