### ISSUE TITLE
Tutors can be added to groups

### ISSUE THREAD

**Issue by WillTheDeveloper** [WillTheDeveloper/StudyPortal#7]
Tutors are able to get added to groups. Which is a problem because whoever created it can add themselves which doesn't actually do anything.

A solution for this would be to update the controller for groups so that the SQL will only get students and not tutors by using the where statement to only select users that are not students. I did previously try this but experienced issues, can follow up.

Maybe this could be a feature but it should at least not allow for tutors to add themselves, this can be confusing.

**Comment by WillTheDeveloper** [comment]
Fixed: https://github.com/WillTheDeveloper/StudyPortal/commit/030631b2c04b26571f7a1c487b4bfc6c2b5d5c8c

Adjusted SQL query to only retrieve users that do not have "is_tutor" cast associated with them or that is true/1.

**Comment by mauro-balades** [comment]
👍🏽
