### ISSUE TITLE
Deleting posts should delete associated data

### ISSUE THREAD

**Issue by WillTheDeveloper** [WillTheDeveloper/StudyPortal#8]
At the moment, posts only delete the post but with no associated data. The view for viewing the posts is still WIP hence why this is something I am pointing out.

Fixes for this can be located in the Community controller as shown below.

![image](https://user-images.githubusercontent.com/78596837/142067432-e8345086-ceab-4964-a742-8c3e24d51480.png)

**Comment by WillTheDeveloper** [comment]
Fixed: https://github.com/WillTheDeveloper/StudyPortal/commit/87575b5d5a7d0148b1c401e26e2fe5c87a506081

**Comment by mauro-balades** [comment]
👍🏽
