### ISSUE TITLE
Can't edit date when updating assignments

### ISSUE THREAD

**Issue by WillTheDeveloper** [WillTheDeveloper/StudyPortal#9]
I think its a cast thing or the data being passed is not understood by the date type of input. Further investigation is required in the specified tag in HTML.

**Comment by WillTheDeveloper** [comment]
Consider this -> https://laravel.com/docs/9.x/requests#old-input

**Comment by mauro-balades** [comment]
Could you please show the line for the HTML tag?

**Comment by WillTheDeveloper** [comment]
@mauro-balades 

It can be found in the "editassignment.blade.php" view.

Beginning on line 40.

I have commented out what would essentially be where you edit the date but I can't get it to work. I believe the format doesn't match.

*I tried adding a code snippet but the formatting was really bad*
